
#include "grng_shader_manager.h"


ID3D11Device												*grng_sm::device = NULL;

GRNG_PISTON<GRNG_SHADER, GRNG_MAX_SHADER_COUNT>				grng_sm::shader;
const GRNG_IPISTON<GRNG_SHADER, GRNG_MAX_SHADER_COUNT>		*grng_sm::ishader;


const std::unordered_map<GRNG_SHADER_TYPE, const LPCSTR>	grng_sm::type_entry_point =
{
	{ GRNG_SHADER_TYPE::GRNG_VERT_SHADER, GRNG_VERT_ENTRY_POINT },
	{ GRNG_SHADER_TYPE::GRNG_GEOM_SHADER, GRNG_GEOM_ENTRY_POINT },
	{ GRNG_SHADER_TYPE::GRNG_FRAG_SHADER, GRNG_FRAG_ENTRY_POINT }
};
const std::unordered_map<GRNG_SHADER_TYPE, const LPCSTR>	grng_sm::type_target =
{
	{ GRNG_SHADER_TYPE::GRNG_VERT_SHADER, GRNG_VERT_TARGET },
	{ GRNG_SHADER_TYPE::GRNG_GEOM_SHADER, GRNG_GEOM_TARGET },
	{ GRNG_SHADER_TYPE::GRNG_FRAG_SHADER, GRNG_FRAG_TARGET }
};
