#pragma once

#include "grng_texture.h"


#define GRNG_MATERIAL_ALBEDO_MAP_SLOT 0u
#define GRNG_MATERIAL_NORMAL_MAP_SLOT 1u
#define GRNG_MATERIAL_ROUGHNESS_MAP_SLOT 2u
#define GRNG_MATERIAL_METALNESS_MAP_SLOT 3u
#define GRNG_MATERIAL_AO_MAP_SLOT 4u
