#pragma once

#include "grng_mesh.h"


#define GRNG_STD_CUBE_OBJ_PATH L"resources/std/grng_cube.obj"

#define GRNG_STD_SPHERE16_OBJ_PATH L"resources/std/grng_sphere16.obj"
#define GRNG_STD_SPHERE32_OBJ_PATH L"resources/std/grng_sphere32.obj"
#define GRNG_STD_SPHERE64_OBJ_PATH L"resources/std/grng_sphere64.obj"


const GRNG_MESH GRNG_STD_CUBE_MESH = GRNG_MESH(GRNG_STD_CUBE_OBJ_PATH, GRNG_MESH_FILE_FORMAT::OBJ);

const GRNG_MESH GRNG_STD_SPHERE16_MESH = GRNG_MESH(GRNG_STD_SPHERE16_OBJ_PATH, GRNG_MESH_FILE_FORMAT::OBJ);
const GRNG_MESH GRNG_STD_SPHERE32_MESH = GRNG_MESH(GRNG_STD_SPHERE32_OBJ_PATH, GRNG_MESH_FILE_FORMAT::OBJ);
const GRNG_MESH GRNG_STD_SPHERE64_MESH = GRNG_MESH(GRNG_STD_SPHERE64_OBJ_PATH, GRNG_MESH_FILE_FORMAT::OBJ);
