#pragma once

#include "rasterizer_state.h"


namespace PULSAR
{
	const PULSAR::RASTERIZER_STATE STD_BACK_FACE_CULL_RS = PULSAR::RASTERIZER_STATE(D3D11_FILL_SOLID, D3D11_CULL_BACK);
	const PULSAR::RASTERIZER_STATE STD_FRONT_FACE_CULL_RS = PULSAR::RASTERIZER_STATE(D3D11_FILL_SOLID, D3D11_CULL_FRONT);
}
