
#include "skybox.h"


PULSAR::VERT_SHADER		PULSAR::SKYBOX::vs = PULSAR::VERT_SHADER(PULSAR::SKYBOX_VS_PATH, PULSAR::VERT_SHADER_ENTRY, NULL);
PULSAR::FRAG_SHADER		PULSAR::SKYBOX::fs = PULSAR::FRAG_SHADER(PULSAR::SKYBOX_FS_PATH, PULSAR::FRAG_SHADER_ENTRY, NULL);

PULSAR::INPUT_LAYOUT	PULSAR::SKYBOX::input_layout;
PULSAR::SAMPLER			PULSAR::SKYBOX::sampler;
