
#include "bindable.h"


PULSAR::PISTON<PULSAR::BINDABLE*, PULSAR::MAX_BINDABLE_COUNT>					PULSAR::BINDABLE::local_unbinds;
const PULSAR::IPISTON<PULSAR::BINDABLE*, PULSAR::MAX_BINDABLE_COUNT>			*PULSAR::BINDABLE::local_iunbinds = PULSAR::BINDABLE::local_unbinds.get_ipiston();

PULSAR::PISTON<PULSAR::BINDABLE*, PULSAR::MAX_BINDABLE_COUNT>					PULSAR::BINDABLE::global_unbinds;
const PULSAR::IPISTON<PULSAR::BINDABLE *, PULSAR::MAX_BINDABLE_COUNT>			*PULSAR::BINDABLE::global_iunbinds = PULSAR::BINDABLE::global_unbinds.get_ipiston();
