
#include "bindable.h"


PULSAR::FIXED_VECTOR<PULSAR::BINDABLE*, PULSAR::MAX_BINDABLE_COUNT>		PULSAR::BINDABLE::local_unbinds;
PULSAR::FIXED_VECTOR<PULSAR::BINDABLE*, PULSAR::MAX_BINDABLE_COUNT>		PULSAR::BINDABLE::global_unbinds;
