#pragma once

namespace PULSAR
{
#define MATERIAL_ALBEDO_MAP_SLOT 0u
#define MATERIAL_NORMAL_MAP_SLOT 1u
#define MATERIAL_ROUGHNESS_MAP_SLOT 2u
#define MATERIAL_METALNESS_MAP_SLOT 3u
#define MATERIAL_AO_MAP_SLOT 4u
#define MATERIAL_EXPOSURE_MAP_SLOT 5u
}
