
#include "camera.h"


PULSAR::FRAG_CONST_BUFFER<PULSAR::CAMERA_DEFERRED_SHADER>		PULSAR::CAMERA::cam_deferred_cbuffer;
PULSAR::CAMERA_DEFERRED_SHADER									PULSAR::CAMERA::cam_deferred_shader;

PULSAR::FRAG_CONST_BUFFER<PULSAR::CAMERA_POST_EFFECTS_SHADER>	PULSAR::CAMERA::cam_post_effects_cbuffer;
PULSAR::CAMERA_POST_EFFECTS_SHADER								PULSAR::CAMERA::cam_post_effects_shader;